### ISSUE TITLE
Error: RPCError 420: FLOOD_PREMIUM_WAIT_3 (caused by SaveBigFilePartRequest)

### ISSUE THREAD

**Issue by Abhi5033** [MiyukiKun/FastTelethonhelper#5]
Hello
I have been using fasttelethon since 8 days and I'm facing below issue since last 4 days
Error: RPCError 420: FLOOD_PREMIUM_WAIT_3 (caused by SaveBigFilePartRequest)

```
code - 1
from FastTelethonhelper import fast_upload
client = TelegramClient(session_name, api_id, api_hash)
await client.connect()

result = await fast_upload(client, file_path)
await client.send_file(group_username, result)
...

code - 2
from FastTelethonhelper import download_file, upload_file
client = TelegramClient(session_name, api_id, api_hash)
await client.connect()

with open(file_path, "rb") as out:
         result = await upload_file(client, out,name=file_path)
...
```

(maybe both codes are same)
using windows 10, uploaded nearly 9-10GB (each file around 500MB to 1GB) using this method and then it started hurting me
Looking at FLOOD_PREMIUM_WAIT_3, I thought I had to wait for 3 seconds, but didn't work, 3 hours wait didn't work
It's been 3 days and I'm still receiving this error
please help

Day 6 : less than 100MB uploads worked with fast upload
Day 7 : 100MB also error now, less than 50MB working with fast upload

**Comment by MiyukiKun** [comment]
The error is Telegram's shitty way of promoting premium evasively.

`telethon.errors.rpc_errors_re += (('FLOOD_PREMIUM_WAIT_(\\d+)', telethon.errors.FloodWaitError),) 
`
add this to the top of your main file to hotfix this issue. untill its fixed from telethon or telegrams side
