### ISSUE TITLE
How to add progress bar for fast upload?

### ISSUE THREAD

**Issue by Abhi5033** [MiyukiKun/FastTelethonhelper#6]
I tried this

```
def progress_callback(current, total):
    progress_bar.n = current
    progress_bar.total = total
    progress_bar.refresh()

progress_bar = tqdm(total=100, unit='B', unit_scale=True, desc='Uploading', leave=False)    
await fast_upload(client, file_path, progress_callback=progress_callback)    
```

But the progress is not working
Please help

**Comment by MiyukiKun** [comment]
The progressbar is for tracing progress from within Telegram. You can look at the default function i made and edit it according to your needs

https://github.com/MiyukiKun/FastTelethonhelper/blob/49e9c5005ff48d07b639fc62a5da5d4688cabf00/FastTelethonhelper/__init__.py#L23
